<?php

namespace AppBundle\Repository;

/**
 * RepoPropertieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepoPropertieRepository extends \Doctrine\ORM\EntityRepository
{
}
