<?php

namespace AppBundle\Repository;

/**
 * UmlFilePropertieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UmlFilePropertieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUmlFileProperties($umlFile)
    {

        $sql = "
                SELECT up.*
                FROM uml_file_propertie up
                WHERE up.uml_file_id = '".$umlFile."'";

        return   $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();
    }
}
