<?php

namespace AppBundle\Repository;

/**
 * UmlFilePropertieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UmlFilePropertieRepository extends \Doctrine\ORM\EntityRepository
{
}
